version: "3.8"
services:
  streamhelper:
    build:
      context: ../
      dockerfile: tools/Dockerfile.dev
      args:
        - PORT=5000
        - DEBUG=0
        - MODE=production
        - BASEDIR=/srv
        - WORKDIR=/srv/app
        - SH_CONFIG_DIR=/srv/config
        - SH_CACHE_DIR=/srv/cache
        - SH_DATA_DIR=/srv/data
        - DATABASE_URL=sqlite:///srv/config/streamhelper.db
        - SH_TEMPLATE_PATH=/srv/data/templates
        - SH_STATIC_PATH=/srv/data/static
        - SH_PLUGIN_PATH=/srv/data/blueprints
        - SH_MACRO_PATH==/srv/data/macros
        - SH_LOG_TYPES=STREAM
        - SH_LOG_LEVEL=WARNING
    image: visiontale/streamhelper
    container_name: streamhelper
    environment:
      - BASEDIR=/srv
      - WORKDIR=/srv/app
      - SH_CONFIG_DIR=/srv/config
      - SH_CACHE_DIR=/srv/cache
      - SH_DATA_DIR=/srv/data
      - DATABASE_URL=sqlite:///srv/config/streamhelper.db
      - SH_TEMPLATE_PATH=/srv/data/templates
      - SH_STATIC_PATH=/srv/data/static
      - SH_PLUGIN_PATH=/srv/data/blueprints
      - SH_MACRO_PATH==/srv/data/macros
      - SH_LOG_TYPES=STREAM
      - SH_LOG_LEVEL=WARNING
    volumes:
      - "../config:/srv/config"
      - "../webapi:/srv/app/webapi:ro"
      - "../webapi.py:/srv/app/webapi.py:ro"
      - "../start.sh:/srv/app/start.sh:ro"
      - "../requirements.txt:/srv/app/requirements.txt:ro"
      - "../migrations:/srv/app/migrations:ro"
      - "../tools:/srv/app/tools:ro"
      - "../templates:/srv/data/templates:ro"
      - "../static:/srv/data/static:ro"
      - "../webapi/blueprints:/srv/data/blueprints:ro"
      - "../webapi/macros:/srv/data/macros:ro"
    ports:
      - "5000:5000"
    networks:
      - streamnet
    restart: unless-stopped

networks:
  streamnet:
    name: streamnet